[project]
name = "space-eval-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faiss-cpu>=1.13.2",
    "langchain>=1.2.8",
    "torch>=2.9.1",
    "transformers>=4.57.6",
    "vllm>=0.15.0",
]
